package com.devgo2003.docgo.contract_service.entity;

import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;
import org.springframework.data.mongodb.core.mapping.Field;
import org.springframework.data.mongodb.core.mapping.DBRef;

import java.time.LocalDateTime;
import java.util.Map;

/**
 * Entity quản lý nhắc nhở và lịch trình cho hợp đồng
 */
@Document(collection = "reminders")
public class Reminder extends BaseEntity {

    @Id
    private String id;

    @Field("contract_id")
    @DBRef
    private Contract contract;

    @Field("title")
    private String title;

    @Field("description")
    private String description;

    @Field("reminder_type")
    private ReminderType reminderType;

    @Field("priority")
    private ReminderPriority priority;

    @Field("status")
    private ReminderStatus status;

    @Field("scheduled_at")
    private LocalDateTime scheduledAt;

    @Field("due_date")
    private LocalDateTime dueDate;

    @Field("recurrence_pattern")
    private RecurrencePattern recurrencePattern;

    @Field("recurrence_interval")
    private Integer recurrenceInterval;

    @Field("recurrence_end_date")
    private LocalDateTime recurrenceEndDate;

    @Field("assigned_to")
    private String assignedTo;

    @Field("assigned_to_name")
    private String assignedToName;

    @Field("assigned_to_email")
    private String assignedToEmail;

    @Field("created_by")
    private String createdBy;

    @Field("created_by_name")
    private String createdByName;

    @Field("notification_channels")
    private String[] notificationChannels;

    @Field("is_escalated")
    private Boolean isEscalated = false;

    @Field("escalation_level")
    private Integer escalationLevel = 0;

    @Field("max_escalation_level")
    private Integer maxEscalationLevel = 3;

    @Field("escalated_at")
    private LocalDateTime escalatedAt;

    @Field("escalated_to")
    private String escalatedTo;

    @Field("completed_at")
    private LocalDateTime completedAt;

    @Field("completed_by")
    private String completedBy;

    @Field("completion_notes")
    private String completionNotes;

    @Field("cancelled_at")
    private LocalDateTime cancelledAt;

    @Field("cancelled_by")
    private String cancelledBy;

    @Field("cancellation_reason")
    private String cancellationReason;

    @Field("last_sent_at")
    private LocalDateTime lastSentAt;

    @Field("sent_count")
    private Integer sentCount = 0;

    @Field("max_send_attempts")
    private Integer maxSendAttempts = 5;

    @Field("custom_data")
    private Map<String, Object> customData;

    @Field("tags")
    private String[] tags;

    @Field("is_auto_generated")
    private Boolean isAutoGenerated = false;

    @Field("source_event")
    private String sourceEvent;

    @Field("related_reminder_id")
    private String relatedReminderId;

    @Override
    public boolean isNew() {
        return this.id == null;
    }

    // Enums
    public enum ReminderType {
        DEADLINE, APPROVAL, REVIEW, RENEWAL, PAYMENT, MEETING, FOLLOW_UP, CUSTOM
    }

    public enum ReminderPriority {
        LOW, MEDIUM, HIGH, URGENT, CRITICAL
    }

    public enum ReminderStatus {
        PENDING, SENT, ACKNOWLEDGED, COMPLETED, CANCELLED, FAILED, ESCALATED
    }

    public enum RecurrencePattern {
        NONE, DAILY, WEEKLY, MONTHLY, QUARTERLY, YEARLY, CUSTOM
    }

    // Constructors
    public Reminder() {
        super();
    }

    public Reminder(Contract contract, String title, String description, 
                   ReminderType reminderType, LocalDateTime scheduledAt) {
        super();
        this.contract = contract;
        this.title = title;
        this.description = description;
        this.reminderType = reminderType;
        this.scheduledAt = scheduledAt;
        this.status = ReminderStatus.PENDING;
        this.priority = ReminderPriority.MEDIUM;
        this.recurrencePattern = RecurrencePattern.NONE;
        this.isEscalated = false;
        this.escalationLevel = 0;
        this.sentCount = 0;
        this.isAutoGenerated = false;
    }

    // Getters and Setters
    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public Contract getContract() {
        return contract;
    }

    public void setContract(Contract contract) {
        this.contract = contract;
    }

    public void setContractId(String contractId) {
        if (this.contract == null) {
            this.contract = new Contract();
        }
        this.contract.setId(contractId);
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public ReminderType getReminderType() {
        return reminderType;
    }

    public void setReminderType(ReminderType reminderType) {
        this.reminderType = reminderType;
    }

    public ReminderPriority getPriority() {
        return priority;
    }

    public void setPriority(ReminderPriority priority) {
        this.priority = priority;
    }

    public ReminderStatus getStatus() {
        return status;
    }

    public void setStatus(ReminderStatus status) {
        this.status = status;
    }

    public LocalDateTime getScheduledAt() {
        return scheduledAt;
    }

    public void setScheduledAt(LocalDateTime scheduledAt) {
        this.scheduledAt = scheduledAt;
    }

    public LocalDateTime getDueDate() {
        return dueDate;
    }

    public void setDueDate(LocalDateTime dueDate) {
        this.dueDate = dueDate;
    }

    public RecurrencePattern getRecurrencePattern() {
        return recurrencePattern;
    }

    public void setRecurrencePattern(RecurrencePattern recurrencePattern) {
        this.recurrencePattern = recurrencePattern;
    }

    public Integer getRecurrenceInterval() {
        return recurrenceInterval;
    }

    public void setRecurrenceInterval(Integer recurrenceInterval) {
        this.recurrenceInterval = recurrenceInterval;
    }

    public LocalDateTime getRecurrenceEndDate() {
        return recurrenceEndDate;
    }

    public void setRecurrenceEndDate(LocalDateTime recurrenceEndDate) {
        this.recurrenceEndDate = recurrenceEndDate;
    }

    public String getAssignedTo() {
        return assignedTo;
    }

    public void setAssignedTo(String assignedTo) {
        this.assignedTo = assignedTo;
    }

    public String getAssignedToName() {
        return assignedToName;
    }

    public void setAssignedToName(String assignedToName) {
        this.assignedToName = assignedToName;
    }

    public String getAssignedToEmail() {
        return assignedToEmail;
    }

    public void setAssignedToEmail(String assignedToEmail) {
        this.assignedToEmail = assignedToEmail;
    }

    public String getCreatedBy() {
        return createdBy;
    }

    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    public String getCreatedByName() {
        return createdByName;
    }

    public void setCreatedByName(String createdByName) {
        this.createdByName = createdByName;
    }

    public String[] getNotificationChannels() {
        return notificationChannels;
    }

    public void setNotificationChannels(String[] notificationChannels) {
        this.notificationChannels = notificationChannels;
    }

    public Boolean getIsEscalated() {
        return isEscalated;
    }

    public void setIsEscalated(Boolean isEscalated) {
        this.isEscalated = isEscalated;
    }

    public Integer getEscalationLevel() {
        return escalationLevel;
    }

    public void setEscalationLevel(Integer escalationLevel) {
        this.escalationLevel = escalationLevel;
    }

    public Integer getMaxEscalationLevel() {
        return maxEscalationLevel;
    }

    public void setMaxEscalationLevel(Integer maxEscalationLevel) {
        this.maxEscalationLevel = maxEscalationLevel;
    }

    public LocalDateTime getEscalatedAt() {
        return escalatedAt;
    }

    public void setEscalatedAt(LocalDateTime escalatedAt) {
        this.escalatedAt = escalatedAt;
    }

    public String getEscalatedTo() {
        return escalatedTo;
    }

    public void setEscalatedTo(String escalatedTo) {
        this.escalatedTo = escalatedTo;
    }

    public LocalDateTime getCompletedAt() {
        return completedAt;
    }

    public void setCompletedAt(LocalDateTime completedAt) {
        this.completedAt = completedAt;
    }

    public String getCompletedBy() {
        return completedBy;
    }

    public void setCompletedBy(String completedBy) {
        this.completedBy = completedBy;
    }

    public String getCompletionNotes() {
        return completionNotes;
    }

    public void setCompletionNotes(String completionNotes) {
        this.completionNotes = completionNotes;
    }

    public LocalDateTime getCancelledAt() {
        return cancelledAt;
    }

    public void setCancelledAt(LocalDateTime cancelledAt) {
        this.cancelledAt = cancelledAt;
    }

    public String getCancelledBy() {
        return cancelledBy;
    }

    public void setCancelledBy(String cancelledBy) {
        this.cancelledBy = cancelledBy;
    }

    public String getCancellationReason() {
        return cancellationReason;
    }

    public void setCancellationReason(String cancellationReason) {
        this.cancellationReason = cancellationReason;
    }

    public LocalDateTime getLastSentAt() {
        return lastSentAt;
    }

    public void setLastSentAt(LocalDateTime lastSentAt) {
        this.lastSentAt = lastSentAt;
    }

    public Integer getSentCount() {
        return sentCount;
    }

    public void setSentCount(Integer sentCount) {
        this.sentCount = sentCount;
    }

    public Integer getMaxSendAttempts() {
        return maxSendAttempts;
    }

    public void setMaxSendAttempts(Integer maxSendAttempts) {
        this.maxSendAttempts = maxSendAttempts;
    }

    public Map<String, Object> getCustomData() {
        return customData;
    }

    public void setCustomData(Map<String, Object> customData) {
        this.customData = customData;
    }

    public String[] getTags() {
        return tags;
    }

    public void setTags(String[] tags) {
        this.tags = tags;
    }

    public Boolean getIsAutoGenerated() {
        return isAutoGenerated;
    }

    public void setIsAutoGenerated(Boolean isAutoGenerated) {
        this.isAutoGenerated = isAutoGenerated;
    }

    public String getSourceEvent() {
        return sourceEvent;
    }

    public void setSourceEvent(String sourceEvent) {
        this.sourceEvent = sourceEvent;
    }

    public String getRelatedReminderId() {
        return relatedReminderId;
    }

    public void setRelatedReminderId(String relatedReminderId) {
        this.relatedReminderId = relatedReminderId;
    }

    // Business methods
    public void send() {
        this.status = ReminderStatus.SENT;
        this.lastSentAt = LocalDateTime.now();
        this.sentCount++;
    }

    public void acknowledge() {
        this.status = ReminderStatus.ACKNOWLEDGED;
    }

    public void complete(String completedBy, String completionNotes) {
        this.status = ReminderStatus.COMPLETED;
        this.completedAt = LocalDateTime.now();
        this.completedBy = completedBy;
        this.completionNotes = completionNotes;
    }

    public void cancel(String cancelledBy, String cancellationReason) {
        this.status = ReminderStatus.CANCELLED;
        this.cancelledAt = LocalDateTime.now();
        this.cancelledBy = cancelledBy;
        this.cancellationReason = cancellationReason;
    }

    public void fail() {
        this.status = ReminderStatus.FAILED;
    }

    public void escalate(String escalatedTo) {
        if (escalationLevel < maxEscalationLevel) {
            this.isEscalated = true;
            this.escalationLevel++;
            this.escalatedAt = LocalDateTime.now();
            this.escalatedTo = escalatedTo;
            this.status = ReminderStatus.ESCALATED;
        }
    }

    public boolean isOverdue() {
        return dueDate != null && LocalDateTime.now().isAfter(dueDate) && 
               (status == ReminderStatus.PENDING || status == ReminderStatus.SENT);
    }

    public boolean canSend() {
        return sentCount < maxSendAttempts && 
               (status == ReminderStatus.PENDING || status == ReminderStatus.FAILED);
    }

    public boolean isRecurring() {
        return recurrencePattern != RecurrencePattern.NONE;
    }

    public boolean shouldRecur() {
        if (!isRecurring()) {
            return false;
        }
        if (recurrenceEndDate != null && LocalDateTime.now().isAfter(recurrenceEndDate)) {
            return false;
        }
        return true;
    }

    public void resetForRecurrence() {
        this.status = ReminderStatus.PENDING;
        this.sentCount = 0;
        this.isEscalated = false;
        this.escalationLevel = 0;
        this.escalatedAt = null;
        this.escalatedTo = null;
        this.completedAt = null;
        this.completedBy = null;
        this.completionNotes = null;
        this.cancelledAt = null;
        this.cancelledBy = null;
        this.cancellationReason = null;
    }
}
