package com.devgo2003.docgo.repository_service.enums;

public enum ContractType {
    SERVICE_AGREEMENT,
    PURCHASE_AGREEMENT,
    PARTNERSHIP_AGREEMENT,
    EMPLOYMENT_CONTRACT,
    SALES_CONTRACT,
    LEASE_AGREEMENT,
    LICENSE_AGREEMENT,
    NON_DISCLOSURE_AGREEMENT,
    SOFTWARE_DEVELOPMENT,
    CONSULTING_AGREEMENT,
    OTHERS
}
