package com.devgo2003.docgo.document_service.service;

import com.devgo2003.docgo.document_service.entity.Reminder;
import com.devgo2003.docgo.document_service.entity.Contract;
import com.devgo2003.docgo.document_service.dto.ReminderCreateRequest;
import com.devgo2003.docgo.document_service.repository.ReminderRepository;
import com.devgo2003.docgo.document_service.repository.ContractRepository;
import com.devgo2003.docgo.document_service.util.PageUtil;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.domain.Page;
import org.springframework.stereotype.Service;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Optional;
import java.util.Map;

@Service
public class ReminderService {

    @Autowired
    private ReminderRepository reminderRepository;

    @Autowired
    private ContractRepository contractRepository;

    public Reminder createReminder(String contractId, String title, String description, 
                                 Reminder.ReminderType reminderType, LocalDateTime scheduledAt) {
        Contract contract = contractRepository.findById(contractId)
                .orElseThrow(() -> new RuntimeException("Contract not found"));
        
        Reminder reminder = new Reminder(contract, title, description, reminderType, scheduledAt);
        reminder.setContractId(contractId);
        reminder.initializeNewEntity();
        
        return reminderRepository.save(reminder);
    }

    public List<Reminder> getRemindersByContractId(String contractId) {
        return reminderRepository.findByContractIdAndIsDeletedFalse(contractId);
    }

    public Optional<Reminder> getReminderById(String id) {
        return reminderRepository.findById(id);
    }

    public List<Reminder> getPendingRemindersByContractId(String contractId) {
        return reminderRepository.findPendingRemindersByContractId(contractId);
    }

    public List<Reminder> getSentRemindersByContractId(String contractId) {
        return reminderRepository.findSentRemindersByContractId(contractId);
    }

    public List<Reminder> getCompletedRemindersByContractId(String contractId) {
        return reminderRepository.findCompletedRemindersByContractId(contractId);
    }

    public List<Reminder> getCancelledRemindersByContractId(String contractId) {
        return reminderRepository.findCancelledRemindersByContractId(contractId);
    }

    public List<Reminder> getFailedRemindersByContractId(String contractId) {
        return reminderRepository.findFailedRemindersByContractId(contractId);
    }

    public List<Reminder> getEscalatedRemindersByContractId(String contractId) {
        return reminderRepository.findEscalatedRemindersByContractId(contractId);
    }

    public List<Reminder> getRemindersByReminderType(String contractId, Reminder.ReminderType reminderType) {
        return reminderRepository.findByContractIdAndReminderTypeAndIsDeletedFalse(contractId, reminderType);
    }

    public List<Reminder> getRemindersByPriority(String contractId, Reminder.ReminderPriority priority) {
        return reminderRepository.findByContractIdAndPriorityAndIsDeletedFalse(contractId, priority);
    }

    public List<Reminder> getNonEscalatedRemindersByContractId(String contractId) {
        return reminderRepository.findNonEscalatedRemindersByContractId(contractId);
    }

    public List<Reminder> getAutoGeneratedRemindersByContractId(String contractId) {
        return reminderRepository.findAutoGeneratedRemindersByContractId(contractId);
    }

    public List<Reminder> getManualRemindersByContractId(String contractId) {
        return reminderRepository.findManualRemindersByContractId(contractId);
    }

    public List<Reminder> getRecurringRemindersByContractId(String contractId) {
        return reminderRepository.findRecurringRemindersByContractId(contractId);
    }

    public List<Reminder> getNonRecurringRemindersByContractId(String contractId) {
        return reminderRepository.findNonRecurringRemindersByContractId(contractId);
    }

    public List<Reminder> getRemindersByContractIdOrderByScheduledAt(String contractId) {
        return reminderRepository.findByContractIdOrderByScheduledAtAsc(contractId);
    }

    public List<Reminder> getRemindersByContractIdOrderByCreatedAt(String contractId) {
        return reminderRepository.findByContractIdOrderByCreatedAtDesc(contractId);
    }

    public List<Reminder> getDueReminders(LocalDateTime currentTime) {
        return reminderRepository.findDueReminders(currentTime);
    }

    public List<Reminder> getOverdueReminders(LocalDateTime currentTime) {
        return reminderRepository.findOverdueReminders(currentTime);
    }

    public List<Reminder> getOverdueRemindersByDueDate(LocalDateTime currentTime) {
        return reminderRepository.findOverdueRemindersByDueDate(currentTime);
    }

    public List<Reminder> getRemindersByScheduledAtBetween(LocalDateTime startDate, LocalDateTime endDate) {
        return reminderRepository.findByScheduledAtBetween(startDate, endDate);
    }

    public List<Reminder> getRemindersByDueDateBetween(LocalDateTime startDate, LocalDateTime endDate) {
        return reminderRepository.findByDueDateBetween(startDate, endDate);
    }

    public List<Reminder> getRemindersByCompletedAtBetween(LocalDateTime startDate, LocalDateTime endDate) {
        return reminderRepository.findByCompletedAtBetween(startDate, endDate);
    }

    public List<Reminder> getRemindersByCancelledAtBetween(LocalDateTime startDate, LocalDateTime endDate) {
        return reminderRepository.findByCancelledAtBetween(startDate, endDate);
    }

    public List<Reminder> getRemindersByEscalatedAtBetween(LocalDateTime startDate, LocalDateTime endDate) {
        return reminderRepository.findByEscalatedAtBetween(startDate, endDate);
    }

    public List<Reminder> getRemindersWithHighSentCount(Integer sentCount) {
        return reminderRepository.findRemindersWithHighSentCount(sentCount);
    }

    public List<Reminder> getRemindersWithHighEscalationLevel(Integer escalationLevel) {
        return reminderRepository.findRemindersWithHighEscalationLevel(escalationLevel);
    }

    public List<Reminder> getRemindersByTags(String contractId, String[] tags) {
        return reminderRepository.findByContractIdAndTagsIn(contractId, tags);
    }

    public List<Reminder> getRemindersBySourceEvent(String contractId, String sourceEvent) {
        return reminderRepository.findByContractIdAndSourceEvent(contractId, sourceEvent);
    }

    public List<Reminder> getRemindersByRelatedReminderId(String contractId, String relatedReminderId) {
        return reminderRepository.findByContractIdAndRelatedReminderId(contractId, relatedReminderId);
    }

    public Reminder sendReminder(String id) {
        Reminder reminder = reminderRepository.findById(id)
                .orElseThrow(() -> new RuntimeException("Reminder not found"));
        
        reminder.send();
        reminder.setUpdatedAt(LocalDateTime.now());
        
        return reminderRepository.save(reminder);
    }

    public Reminder acknowledgeReminder(String id) {
        Reminder reminder = reminderRepository.findById(id)
                .orElseThrow(() -> new RuntimeException("Reminder not found"));
        
        reminder.acknowledge();
        reminder.setUpdatedAt(LocalDateTime.now());
        
        return reminderRepository.save(reminder);
    }

    public Reminder completeReminder(String id, String completedBy, String completionNotes) {
        Reminder reminder = reminderRepository.findById(id)
                .orElseThrow(() -> new RuntimeException("Reminder not found"));
        
        reminder.complete(completedBy, completionNotes);
        reminder.setUpdatedAt(LocalDateTime.now());
        
        return reminderRepository.save(reminder);
    }

    public Reminder cancelReminder(String id, String cancelledBy, String cancellationReason) {
        Reminder reminder = reminderRepository.findById(id)
                .orElseThrow(() -> new RuntimeException("Reminder not found"));
        
        reminder.cancel(cancelledBy, cancellationReason);
        reminder.setUpdatedAt(LocalDateTime.now());
        
        return reminderRepository.save(reminder);
    }

    public Reminder failReminder(String id) {
        Reminder reminder = reminderRepository.findById(id)
                .orElseThrow(() -> new RuntimeException("Reminder not found"));
        
        reminder.fail();
        reminder.setUpdatedAt(LocalDateTime.now());
        
        return reminderRepository.save(reminder);
    }

    public Reminder escalateReminder(String id, String escalatedTo) {
        Reminder reminder = reminderRepository.findById(id)
                .orElseThrow(() -> new RuntimeException("Reminder not found"));
        
        reminder.escalate(escalatedTo);
        reminder.setUpdatedAt(LocalDateTime.now());
        
        return reminderRepository.save(reminder);
    }

    public Reminder resetForRecurrence(String id) {
        Reminder reminder = reminderRepository.findById(id)
                .orElseThrow(() -> new RuntimeException("Reminder not found"));
        
        reminder.resetForRecurrence();
        reminder.setUpdatedAt(LocalDateTime.now());
        
        return reminderRepository.save(reminder);
    }

    public Reminder setScheduledAt(String id, LocalDateTime scheduledAt) {
        Reminder reminder = reminderRepository.findById(id)
                .orElseThrow(() -> new RuntimeException("Reminder not found"));
        
        reminder.setScheduledAt(scheduledAt);
        reminder.setUpdatedAt(LocalDateTime.now());
        
        return reminderRepository.save(reminder);
    }

    public Reminder setDueDate(String id, LocalDateTime dueDate) {
        Reminder reminder = reminderRepository.findById(id)
                .orElseThrow(() -> new RuntimeException("Reminder not found"));
        
        reminder.setDueDate(dueDate);
        reminder.setUpdatedAt(LocalDateTime.now());
        
        return reminderRepository.save(reminder);
    }

    public Reminder setPriority(String id, Reminder.ReminderPriority priority) {
        Reminder reminder = reminderRepository.findById(id)
                .orElseThrow(() -> new RuntimeException("Reminder not found"));
        
        reminder.setPriority(priority);
        reminder.setUpdatedAt(LocalDateTime.now());
        
        return reminderRepository.save(reminder);
    }

    public Reminder setRecurrencePattern(String id, Reminder.RecurrencePattern recurrencePattern, 
                                       Integer recurrenceInterval, LocalDateTime recurrenceEndDate) {
        Reminder reminder = reminderRepository.findById(id)
                .orElseThrow(() -> new RuntimeException("Reminder not found"));
        
        reminder.setRecurrencePattern(recurrencePattern);
        reminder.setRecurrenceInterval(recurrenceInterval);
        reminder.setRecurrenceEndDate(recurrenceEndDate);
        reminder.setUpdatedAt(LocalDateTime.now());
        
        return reminderRepository.save(reminder);
    }

    public Reminder setAssignedTo(String id, String assignedTo, String assignedToName, String assignedToEmail) {
        Reminder reminder = reminderRepository.findById(id)
                .orElseThrow(() -> new RuntimeException("Reminder not found"));
        
        reminder.setAssignedTo(assignedTo);
        reminder.setAssignedToName(assignedToName);
        reminder.setAssignedToEmail(assignedToEmail);
        reminder.setUpdatedAt(LocalDateTime.now());
        
        return reminderRepository.save(reminder);
    }

    public Reminder setNotificationChannels(String id, String[] notificationChannels) {
        Reminder reminder = reminderRepository.findById(id)
                .orElseThrow(() -> new RuntimeException("Reminder not found"));
        
        reminder.setNotificationChannels(notificationChannels);
        reminder.setUpdatedAt(LocalDateTime.now());
        
        return reminderRepository.save(reminder);
    }

    public Reminder setCustomData(String id, Map<String, Object> customData) {
        Reminder reminder = reminderRepository.findById(id)
                .orElseThrow(() -> new RuntimeException("Reminder not found"));
        
        reminder.setCustomData(customData);
        reminder.setUpdatedAt(LocalDateTime.now());
        
        return reminderRepository.save(reminder);
    }

    public Reminder setTags(String id, String[] tags) {
        Reminder reminder = reminderRepository.findById(id)
                .orElseThrow(() -> new RuntimeException("Reminder not found"));
        
        reminder.setTags(tags);
        reminder.setUpdatedAt(LocalDateTime.now());
        
        return reminderRepository.save(reminder);
    }

    public Reminder setSourceEvent(String id, String sourceEvent) {
        Reminder reminder = reminderRepository.findById(id)
                .orElseThrow(() -> new RuntimeException("Reminder not found"));
        
        reminder.setSourceEvent(sourceEvent);
        reminder.setUpdatedAt(LocalDateTime.now());
        
        return reminderRepository.save(reminder);
    }

    public Reminder setRelatedReminderId(String id, String relatedReminderId) {
        Reminder reminder = reminderRepository.findById(id)
                .orElseThrow(() -> new RuntimeException("Reminder not found"));
        
        reminder.setRelatedReminderId(relatedReminderId);
        reminder.setUpdatedAt(LocalDateTime.now());
        
        return reminderRepository.save(reminder);
    }

    public void deleteReminder(String id, String deletedBy) {
        Reminder reminder = reminderRepository.findById(id)
                .orElseThrow(() -> new RuntimeException("Reminder not found"));
        
        reminder.markAsDeleted(deletedBy);
        reminder.setUpdatedAt(LocalDateTime.now());
        
        reminderRepository.save(reminder);
    }

    public Reminder restoreReminder(String id) {
        Reminder reminder = reminderRepository.findById(id)
                .orElseThrow(() -> new RuntimeException("Reminder not found"));
        
        reminder.restore();
        reminder.setUpdatedAt(LocalDateTime.now());
        
        return reminderRepository.save(reminder);
    }

    public long countRemindersByContractId(String contractId) {
        return reminderRepository.countByContractIdAndIsDeletedFalse(contractId);
    }

    public long countRemindersByContractIdAndStatus(String contractId, Reminder.ReminderStatus status) {
        return reminderRepository.countByContractIdAndStatusAndIsDeletedFalse(contractId, status);
    }

    public long countRemindersByAssignedTo(String assignedTo) {
        return reminderRepository.countByAssignedToAndIsDeletedFalse(assignedTo);
    }

    public long countRemindersByCreatedBy(String createdBy) {
        return reminderRepository.countByCreatedByAndIsDeletedFalse(createdBy);
    }

    public long countPendingRemindersByContractId(String contractId) {
        return reminderRepository.countPendingRemindersByContractId(contractId);
    }

    public long countSentRemindersByContractId(String contractId) {
        return reminderRepository.countSentRemindersByContractId(contractId);
    }

    public long countCompletedRemindersByContractId(String contractId) {
        return reminderRepository.countCompletedRemindersByContractId(contractId);
    }

    public long countCancelledRemindersByContractId(String contractId) {
        return reminderRepository.countCancelledRemindersByContractId(contractId);
    }

    public long countFailedRemindersByContractId(String contractId) {
        return reminderRepository.countFailedRemindersByContractId(contractId);
    }

    public long countEscalatedRemindersByContractId(String contractId) {
        return reminderRepository.countEscalatedRemindersByContractId(contractId);
    }

    public long countNonEscalatedRemindersByContractId(String contractId) {
        return reminderRepository.countNonEscalatedRemindersByContractId(contractId);
    }

    public long countAutoGeneratedRemindersByContractId(String contractId) {
        return reminderRepository.countAutoGeneratedRemindersByContractId(contractId);
    }

    public long countManualRemindersByContractId(String contractId) {
        return reminderRepository.countManualRemindersByContractId(contractId);
    }

    public long countRecurringRemindersByContractId(String contractId) {
        return reminderRepository.countRecurringRemindersByContractId(contractId);
    }

    public long countNonRecurringRemindersByContractId(String contractId) {
        return reminderRepository.countNonRecurringRemindersByContractId(contractId);
    }

    public boolean existsRemindersByContractId(String contractId) {
        return reminderRepository.existsByContractIdAndIsDeletedFalse(contractId);
    }

    public boolean existsPendingRemindersByContractId(String contractId) {
        return reminderRepository.existsPendingRemindersByContractId(contractId);
    }

    public boolean existsSentRemindersByContractId(String contractId) {
        return reminderRepository.existsSentRemindersByContractId(contractId);
    }

    public boolean existsCompletedRemindersByContractId(String contractId) {
        return reminderRepository.existsCompletedRemindersByContractId(contractId);
    }

    public boolean existsCancelledRemindersByContractId(String contractId) {
        return reminderRepository.existsCancelledRemindersByContractId(contractId);
    }

    public boolean existsFailedRemindersByContractId(String contractId) {
        return reminderRepository.existsFailedRemindersByContractId(contractId);
    }

    public boolean existsEscalatedRemindersByContractId(String contractId) {
        return reminderRepository.existsEscalatedRemindersByContractId(contractId);
    }

    public boolean existsNonEscalatedRemindersByContractId(String contractId) {
        return reminderRepository.existsNonEscalatedRemindersByContractId(contractId);
    }

    public boolean existsAutoGeneratedRemindersByContractId(String contractId) {
        return reminderRepository.existsAutoGeneratedRemindersByContractId(contractId);
    }

    public boolean existsManualRemindersByContractId(String contractId) {
        return reminderRepository.existsManualRemindersByContractId(contractId);
    }

    public boolean existsRecurringRemindersByContractId(String contractId) {
        return reminderRepository.existsRecurringRemindersByContractId(contractId);
    }

    public boolean existsNonRecurringRemindersByContractId(String contractId) {
        return reminderRepository.existsNonRecurringRemindersByContractId(contractId);
    }

    /**
     * Tạo reminder mới từ ReminderCreateRequest
     */
    public Reminder createReminder(ReminderCreateRequest request) {
        Contract contract = contractRepository.findById(request.getContractId())
                .orElseThrow(() -> new RuntimeException("Contract not found"));
        
        Reminder reminder = new Reminder(contract, request.getTitle(), request.getDescription(), 
                                       request.getReminderType(), request.getReminderDate());
        reminder.setContractId(request.getContractId());
        // Note: Reminder entity may not have these methods, skip for now
        // reminder.setIsRecurring(request.getIsRecurring());
        // reminder.setRecurringPattern(request.getRecurringPattern());
        // reminder.setRecipientEmail(request.getRecipientEmail());
        // reminder.setRecipientPhone(request.getRecipientPhone());
        // reminder.setNotificationMethod(request.getNotificationMethod());
        // reminder.setPriority(request.getPriority());
        // reminder.setAdditionalData(request.getAdditionalData());
        reminder.initializeNewEntity();
        
        return reminderRepository.save(reminder);
    }

    /**
     * Lấy tất cả reminder
     */
    public List<Reminder> getAllReminders() {
        return reminderRepository.findAll();
    }

    /**
     * Lấy tất cả reminder với pagination và filtering
     */
    public Page<Reminder> getAllReminders(int pageNumber, int pageSize, String sortBy, String sortDirection, boolean includeDeleted) {
        // Get all reminders
        List<Reminder> allReminders = reminderRepository.findAll();
        
        // Convert to Page using PageUtil
        return PageUtil.createPageFromList(allReminders, pageNumber, pageSize, sortBy, sortDirection);
    }
}
