filebeat.inputs:
  - type: container
    enabled: true
    paths:
      - /var/lib/docker/containers/*/*.log
    processors:
      - add_docker_metadata: ~
      - decode_json_fields:
          fields: ["message"]
          target: "json"
          overwrite_keys: true
          add_error_key: true

processors:
  - add_host_metadata: ~
  - add_cloud_metadata: ~
  - drop_event:
      when:
        or:
          - equals:
              container.name: "docgo-local-filebeat"
          - equals:
              container.image.name: "docker.elastic.co/beats/filebeat:8.11.0"

output.elasticsearch:
  hosts: ["elasticsearch:9200"]
  protocol: "http"
  ssl:
    enabled: false
  indices:
    - index: "docgo-logs-%{+yyyy.MM.dd}"

setup.template.name: "docgo-logs"
setup.template.pattern: "docgo-logs-*"
setup.ilm.enabled: false

setup.kibana:
  host: "kibana:5601"

