package com.devgo2003.docgo.contract_service.repository;

import com.devgo2003.docgo.contract_service.entity.Reminder;
import org.springframework.data.mongodb.repository.MongoRepository;
import org.springframework.data.mongodb.repository.Query;
import org.springframework.stereotype.Repository;

import java.time.LocalDateTime;
import java.util.List;

@Repository
public interface ReminderRepository extends MongoRepository<Reminder, String> {

    List<Reminder> findByContractIdAndIsDeletedFalse(String contractId);
    
    List<Reminder> findByContractIdAndStatusAndIsDeletedFalse(String contractId, Reminder.ReminderStatus status);
    
    List<Reminder> findByAssignedToAndIsDeletedFalse(String assignedTo);
    
    List<Reminder> findByCreatedByAndIsDeletedFalse(String createdBy);
    
    @Query("{ 'contractId': ?0, 'status': 'PENDING', 'isDeleted': false }")
    List<Reminder> findPendingRemindersByContractId(String contractId);
    
    @Query("{ 'contractId': ?0, 'status': 'SENT', 'isDeleted': false }")
    List<Reminder> findSentRemindersByContractId(String contractId);
    
    @Query("{ 'contractId': ?0, 'status': 'COMPLETED', 'isDeleted': false }")
    List<Reminder> findCompletedRemindersByContractId(String contractId);
    
    @Query("{ 'contractId': ?0, 'status': 'CANCELLED', 'isDeleted': false }")
    List<Reminder> findCancelledRemindersByContractId(String contractId);
    
    @Query("{ 'contractId': ?0, 'status': 'FAILED', 'isDeleted': false }")
    List<Reminder> findFailedRemindersByContractId(String contractId);
    
    @Query("{ 'contractId': ?0, 'status': 'ESCALATED', 'isDeleted': false }")
    List<Reminder> findEscalatedRemindersByContractId(String contractId);
    
    List<Reminder> findByContractIdAndReminderTypeAndIsDeletedFalse(String contractId, Reminder.ReminderType reminderType);
    
    List<Reminder> findByContractIdAndPriorityAndIsDeletedFalse(String contractId, Reminder.ReminderPriority priority);
    
    
    @Query("{ 'contractId': ?0, 'isEscalated': false, 'isDeleted': false }")
    List<Reminder> findNonEscalatedRemindersByContractId(String contractId);
    
    @Query("{ 'contractId': ?0, 'isAutoGenerated': true, 'isDeleted': false }")
    List<Reminder> findAutoGeneratedRemindersByContractId(String contractId);
    
    @Query("{ 'contractId': ?0, 'isAutoGenerated': false, 'isDeleted': false }")
    List<Reminder> findManualRemindersByContractId(String contractId);
    
    @Query("{ 'contractId': ?0, 'recurrencePattern': { $ne: 'NONE' }, 'isDeleted': false }")
    List<Reminder> findRecurringRemindersByContractId(String contractId);
    
    @Query("{ 'contractId': ?0, 'recurrencePattern': 'NONE', 'isDeleted': false }")
    List<Reminder> findNonRecurringRemindersByContractId(String contractId);
    
    @Query("{ 'contractId': ?0, 'isDeleted': false }")
    List<Reminder> findByContractIdOrderByScheduledAtAsc(String contractId);
    
    @Query("{ 'contractId': ?0, 'isDeleted': false }")
    List<Reminder> findByContractIdOrderByCreatedAtDesc(String contractId);
    
    @Query("{ 'scheduledAt': { $lte: ?0 }, 'status': 'PENDING', 'isDeleted': false }")
    List<Reminder> findDueReminders(LocalDateTime currentTime);
    
    @Query("{ 'scheduledAt': { $lte: ?0 }, 'status': 'PENDING', 'isDeleted': false }")
    List<Reminder> findOverdueReminders(LocalDateTime currentTime);
    
    @Query("{ 'dueDate': { $lte: ?0 }, 'status': { $in: ['PENDING', 'SENT'] }, 'isDeleted': false }")
    List<Reminder> findOverdueRemindersByDueDate(LocalDateTime currentTime);
    
    @Query("{ 'scheduledAt': { $gte: ?0, $lte: ?1 }, 'isDeleted': false }")
    List<Reminder> findByScheduledAtBetween(LocalDateTime startDate, LocalDateTime endDate);
    
    @Query("{ 'dueDate': { $gte: ?0, $lte: ?1 }, 'isDeleted': false }")
    List<Reminder> findByDueDateBetween(LocalDateTime startDate, LocalDateTime endDate);
    
    @Query("{ 'completedAt': { $gte: ?0, $lte: ?1 }, 'status': 'COMPLETED', 'isDeleted': false }")
    List<Reminder> findByCompletedAtBetween(LocalDateTime startDate, LocalDateTime endDate);
    
    @Query("{ 'cancelledAt': { $gte: ?0, $lte: ?1 }, 'status': 'CANCELLED', 'isDeleted': false }")
    List<Reminder> findByCancelledAtBetween(LocalDateTime startDate, LocalDateTime endDate);
    
    @Query("{ 'escalatedAt': { $gte: ?0, $lte: ?1 }, 'status': 'ESCALATED', 'isDeleted': false }")
    List<Reminder> findByEscalatedAtBetween(LocalDateTime startDate, LocalDateTime endDate);
    
    @Query("{ 'sentCount': { $gt: ?0 }, 'isDeleted': false }")
    List<Reminder> findRemindersWithHighSentCount(Integer sentCount);
    
    @Query("{ 'escalationLevel': { $gt: ?0 }, 'isDeleted': false }")
    List<Reminder> findRemindersWithHighEscalationLevel(Integer escalationLevel);
    
    @Query("{ 'contractId': ?0, 'tags': { $in: [?1] }, 'isDeleted': false }")
    List<Reminder> findByContractIdAndTagsIn(String contractId, String[] tags);
    
    @Query("{ 'contractId': ?0, 'sourceEvent': ?1, 'isDeleted': false }")
    List<Reminder> findByContractIdAndSourceEvent(String contractId, String sourceEvent);
    
    @Query("{ 'contractId': ?0, 'relatedReminderId': ?1, 'isDeleted': false }")
    List<Reminder> findByContractIdAndRelatedReminderId(String contractId, String relatedReminderId);
    
    long countByContractIdAndIsDeletedFalse(String contractId);
    
    long countByContractIdAndStatusAndIsDeletedFalse(String contractId, Reminder.ReminderStatus status);
    
    long countByAssignedToAndIsDeletedFalse(String assignedTo);
    
    long countByCreatedByAndIsDeletedFalse(String createdBy);
    
    @Query("{ 'contractId': ?0, 'status': 'PENDING', 'isDeleted': false }")
    long countPendingRemindersByContractId(String contractId);
    
    @Query("{ 'contractId': ?0, 'status': 'SENT', 'isDeleted': false }")
    long countSentRemindersByContractId(String contractId);
    
    @Query("{ 'contractId': ?0, 'status': 'COMPLETED', 'isDeleted': false }")
    long countCompletedRemindersByContractId(String contractId);
    
    @Query("{ 'contractId': ?0, 'status': 'CANCELLED', 'isDeleted': false }")
    long countCancelledRemindersByContractId(String contractId);
    
    @Query("{ 'contractId': ?0, 'status': 'FAILED', 'isDeleted': false }")
    long countFailedRemindersByContractId(String contractId);
    
    @Query("{ 'contractId': ?0, 'status': 'ESCALATED', 'isDeleted': false }")
    long countEscalatedRemindersByContractId(String contractId);
    
    
    @Query("{ 'contractId': ?0, 'isEscalated': false, 'isDeleted': false }")
    long countNonEscalatedRemindersByContractId(String contractId);
    
    @Query("{ 'contractId': ?0, 'isAutoGenerated': true, 'isDeleted': false }")
    long countAutoGeneratedRemindersByContractId(String contractId);
    
    @Query("{ 'contractId': ?0, 'isAutoGenerated': false, 'isDeleted': false }")
    long countManualRemindersByContractId(String contractId);
    
    @Query("{ 'contractId': ?0, 'recurrencePattern': { $ne: 'NONE' }, 'isDeleted': false }")
    long countRecurringRemindersByContractId(String contractId);
    
    @Query("{ 'contractId': ?0, 'recurrencePattern': 'NONE', 'isDeleted': false }")
    long countNonRecurringRemindersByContractId(String contractId);
    
    long countByContractIdAndReminderTypeAndIsDeletedFalse(String contractId, Reminder.ReminderType reminderType);
    
    long countByContractIdAndPriorityAndIsDeletedFalse(String contractId, Reminder.ReminderPriority priority);
    
    boolean existsByContractIdAndIsDeletedFalse(String contractId);
    
    @Query("{ 'contractId': ?0, 'status': 'PENDING', 'isDeleted': false }")
    boolean existsPendingRemindersByContractId(String contractId);
    
    @Query("{ 'contractId': ?0, 'status': 'SENT', 'isDeleted': false }")
    boolean existsSentRemindersByContractId(String contractId);
    
    @Query("{ 'contractId': ?0, 'status': 'COMPLETED', 'isDeleted': false }")
    boolean existsCompletedRemindersByContractId(String contractId);
    
    @Query("{ 'contractId': ?0, 'status': 'CANCELLED', 'isDeleted': false }")
    boolean existsCancelledRemindersByContractId(String contractId);
    
    @Query("{ 'contractId': ?0, 'status': 'FAILED', 'isDeleted': false }")
    boolean existsFailedRemindersByContractId(String contractId);
    
    @Query("{ 'contractId': ?0, 'status': 'ESCALATED', 'isDeleted': false }")
    boolean existsEscalatedRemindersByContractId(String contractId);
    
    
    @Query("{ 'contractId': ?0, 'isEscalated': false, 'isDeleted': false }")
    boolean existsNonEscalatedRemindersByContractId(String contractId);
    
    @Query("{ 'contractId': ?0, 'isAutoGenerated': true, 'isDeleted': false }")
    boolean existsAutoGeneratedRemindersByContractId(String contractId);
    
    @Query("{ 'contractId': ?0, 'isAutoGenerated': false, 'isDeleted': false }")
    boolean existsManualRemindersByContractId(String contractId);
    
    @Query("{ 'contractId': ?0, 'recurrencePattern': { $ne: 'NONE' }, 'isDeleted': false }")
    boolean existsRecurringRemindersByContractId(String contractId);
    
    @Query("{ 'contractId': ?0, 'recurrencePattern': 'NONE', 'isDeleted': false }")
    boolean existsNonRecurringRemindersByContractId(String contractId);
}
