spring.application.name=auth-service
# Server
server.port=8001

# Database Configuration (Docker)
spring.datasource.url=jdbc:mariadb://mariadb:3306/docgo
spring.datasource.username=docgo_user
spring.datasource.password=docgo_password
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# JPA/Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect

# Logging
logging.level.org.springframework=INFO
logging.level.com.devgo2003.docgo.auth_service=DEBUG

# Swagger/OpenAPI
springdoc.swagger-ui.path=/docs
springdoc.swagger-ui.enabled=true
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.config-url=/v3/api-docs/swagger-config
springdoc.swagger-ui.url=/v3/api-docs

# Redirect configuration
spring.mvc.throw-exception-if-no-handler-found=true
spring.web.resources.add-mappings=true
