// Centralized route configuration
import {
  LOGIN_PATH,
  REGISTER_PATH,
  LANDING_HOME_PATH,
  DASHBOARD_PATH,
  REPOSITORIES_PATH,
  REPOSITORY_DETAIL_PATH,
  REPOSITORY_FILE_DETAIL_PATH,
  REPOSITORY_FILES_LIST_PATH,
  ORGANIZATIONS_PATH,
  ORGANIZATION_DETAIL_PATH,
  ORGANIZATION_WORKSPACE_PATH,
  ORGANIZATION_MEMBERS_PATH,
  ACCEPT_INVITATION_PATH,
  PROFILE_PATH,
  SETTINGS_PATH,
  NOT_FOUND_PATH,
  UNAUTHORIZED_PATH,
} from '@constants';

export const PUBLIC_ROUTES = {
  LOGIN: LOGIN_PATH,
  REGISTER: REGISTER_PATH,
  HOME: LANDING_HOME_PATH,
  ACCEPT_INVITATION: ACCEPT_INVITATION_PATH,
} as const;

export const PROTECTED_ROUTES = {
  DASHBOARD: DASHBOARD_PATH,
  REPOSITORIES: REPOSITORIES_PATH,
  REPOSITORY_FILES_LIST: REPOSITORY_FILES_LIST_PATH,
  REPOSITORY_DETAIL: REPOSITORY_DETAIL_PATH,
  REPOSITORY_FILE_DETAIL: REPOSITORY_FILE_DETAIL_PATH,
  UPLOAD: '/upload',
  ORGANIZATIONS: ORGANIZATIONS_PATH,
  ORGANIZATION_DETAIL: ORGANIZATION_DETAIL_PATH,
  ORGANIZATION_WORKSPACE: ORGANIZATION_WORKSPACE_PATH,
  ORGANIZATION_MEMBERS: ORGANIZATION_MEMBERS_PATH,
  PROFILE: PROFILE_PATH,
  SETTINGS: SETTINGS_PATH,
};

export const ERROR_ROUTES = {
  UNAUTHORIZED: UNAUTHORIZED_PATH,
  NOT_FOUND: NOT_FOUND_PATH,
};

export const OAUTH_ROUTES = {
  CALLBACK: '/auth/oauth2/callback',
  CALLBACK_ALT: '/oauth2/callback',
};

export const ALL_ROUTES = {
  ...PUBLIC_ROUTES,
  ...PROTECTED_ROUTES,
  ...ERROR_ROUTES,
  ...OAUTH_ROUTES,
};
